version: '3.3'

services:
  zookeeper:
    image: wurstmeister/zookeeper
    ports:
      - "2181:2181"
  kafka:
    image: wurstmeister/kafka
    ports:
      - "9092:9092"
    environment:
      KAFKA_ADVERTISED_HOST_NAME: 172.20.0.1
      KAFKA_CREATE_TOPICS: "test:1:1,RawGbt:1:1,StratumJob:1:1,SolvedShare:1:1,ShareLog:1:1,CommonEvents:1:1,NMCAuxBlock:1:1,NMCSolvedShare:1:1"
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
  btcpool:
    image: daocloud.io/dubuqingfeng/btcpool
    volumes:
      - ./sserver.cfg:/work/btcpool/build/run_sserver/sserver.cfg
    container_name: btcpool
    command: /work/btcpool/build/run_sserver/sserver -c /work/btcpool/build/run_sserver/sserver.cfg -l /work/btcpool/build/run_sserver/log_sserver