version: '3.3'
# networks:
#   btcpool:

services:
  zookeeper:
    image: wurstmeister/zookeeper
    ports:
      - "2181:2181"
  kafka:
    image: wurstmeister/kafka
    ports:
      - "9092:9092"
    environment:
      KAFKA_CREATE_TOPICS: "test:1:1,RawGbt:1:1,StratumJob:1:1,SolvedShare:1:1,ShareLog:1:1,CommonEvents:1:1,NMCAuxBlock:1:1,NMCSolvedShare:1:1"
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
  kafka-manager:  
    image: sheepkiller/kafka-manager
    environment:
        ZK_HOSTS: zookeeper:2181
    ports:
      - "9000:9000"          
  btcpool-sserver:
    image: daocloud.io/dubuqingfeng/btcpool
    volumes:
      - ./config/sserver.cfg:/work/btcpool/build/run_sserver/sserver.cfg
      - ./config/jobmaker.cfg:/work/btcpool/build/run_jobmaker/jobmaker.cfg
      - ./config/blkmaker.cfg:/work/btcpool/build/run_blkmaker/blkmaker.cfg
      - ./config/gbtmaker.cfg:/work/btcpool/build/run_gbtmaker/gbtmaker.cfg
      - ./config/statshttpd.cfg:/work/btcpool/build/run_statshttpd/statshttpd.cfg
      - ./config/sharelogger.cfg:/work/btcpool/build/run_sharelogger/sharelogger.cfg
    container_name: btcpool
    depends_on:
      - kafka
    ports:
      - "3333:3333"
    # command: /work/btcpool/build/run_sserver/sserver -c /work/btcpool/build/run_sserver/sserver.cfg -l /work/btcpool/build/run_sserver/log_sserver
    # command: /work/btcpool/build/run_jobmaker/jobmaker -c /work/btcpool/build/run_jobmaker/jobmaker.cfg -l /work/btcpool/build/run_jobmaker/log_jobmaker
    command: tail -f /dev/null