version: '3.3'
# networks:
#   btcpool:

services:
  bitcoind:
    image: dubuqingfeng/btcpool-bitcoin:bitcoind-0.16.3
    volumes:
      - ~/Downloads/testnet3:/root/.bitcoin
    ports:
      - "8333:8333"
      - "8332:8332"
      - "8331:8331"
      - "18333:18333"
      - "18332:18332"
      - "18331:18331"
    container_name: bitcoind-0.16.3
    command: bitcoind -testnet -conf="/root/.bitcoin/bitcoin.conf" -datadir="/root/.bitcoin" -zmqpubrawblock=tcp://0.0.0.0:18331 -zmqpubrawtx=tcp://0.0.0.0:18331 -zmqpubhashtx=tcp://0.0.0.0:18331 -zmqpubhashblock=tcp://0.0.0.0:18331
  zookeeper:
    image: bitnami/zookeeper:latest
    container_name: btcpool_zookeeper
    ports:
      - "2181:2181"
    environment:
      - ALLOW_ANONYMOUS_LOGIN=yes
  kafka:
    image: bitnami/kafka:latest
    container_name: btcpool_kafka
    ports:
      - "9092:9092"
    environment:
      - KAFKA_ZOOKEEPER_CONNECT=zookeeper:2181
      - ALLOW_PLAINTEXT_LISTENER=yes
  btcpool-sserver:
    image: daocloud.io/dubuqingfeng/btcpool
    volumes:
      - ./configs/sserver.cfg:/work/btcpool/build/run_sserver/sserver.cfg
      - ./configs/jobmaker.cfg:/work/btcpool/build/run_jobmaker/jobmaker.cfg
      - ./configs/nmcauxmaker.cfg:/work/btcpool/build/run_nmcauxmaker/nmcauxmaker.cfg
      - ./configs/blkmaker.cfg:/work/btcpool/build/run_blkmaker/blkmaker.cfg
      - ./configs/gbtmaker.cfg:/work/btcpool/build/run_gbtmaker/gbtmaker.cfg
      - ./configs/gwmaker.cfg:/work/btcpool/build/run_gwmaker/gwmaker.cfg
      - ./configs/statshttpd.cfg:/work/btcpool/build/run_statshttpd/statshttpd.cfg
      - ./configs/sharelogger.cfg:/work/btcpool/build/run_sharelogger/sharelogger.cfg
      - ./configs/slparser.cfg:/work/btcpool/build/run_slparser/slparser.cfg
      - ./configs/poolwatcher.cfg:/work/btcpool/build/run_poolwatcher/poolwatcher.cfg
      - ./configs/simulator.cfg:/work/btcpool/build/run_simulator/simulator.cfg
    container_name: btcpool_sserver
    depends_on:
      - kafka
    ports:
      - "3333:3333"
    # command: /work/btcpool/build/run_sserver/sserver -c /work/btcpool/build/run_sserver/sserver.cfg -l /work/btcpool/build/run_sserver/log_sserver
    # command: /work/btcpool/build/run_jobmaker/jobmaker -c /work/btcpool/build/run_jobmaker/jobmaker.cfg -l /work/btcpool/build/run_jobmaker/log_jobmaker
    # command: /work/btcpool/build/run_blkmaker/blkmaker -c /work/btcpool/build/run_blkmaker/blkmaker.cfg -l /work/btcpool/build/run_blkmaker/log_blkmaker
    # command: /work/btcpool/build/run_gbtmaker/gbtmaker -c /work/btcpool/build/run_gbtmaker/gbtmaker.cfg -l /work/btcpool/build/run_gbtmaker/log_gbtmaker
    # command: /work/btcpool/build/run_statshttpd/statshttpd -c /work/btcpool/build/run_statshttpd/statshttpd.cfg -l /work/btcpool/build/run_statshttpd/log_statshttpd
    # command: /work/btcpool/build/run_sharelogger/sharelogger -c /work/btcpool/build/run_sharelogger/sharelogger.cfg -l /work/btcpool/build/run_sharelogger/log_sharelogger
    # command: /work/btcpool/build/run_slparser/sharelogger -c /work/btcpool/build/run_slparser/slparser.cfg -l /work/btcpool/build/run_slparser/log_slparser
    # command: /work/btcpool/build/run_poolwatcher/poolwatcher -c /work/btcpool/build/run_poolwatcher/poolwatcher.cfg -l /work/btcpool/build/run_poolwatcher/log_poolwatcher
    # command: /work/btcpool/build/run_gwmaker/gwmaker -c /work/btcpool/build/run_gwmaker/gwmaker.cfg -l /work/btcpool/build/run_gwmaker/log_gwmaker
    # command: /work/btcpool/build/run_nmcauxmaker/nmcauxmaker -c /work/btcpool/build/run_nmcauxmaker/nmcauxmaker.cfg -l /work/btcpool/build/run_nmcauxmaker/log_nmcauxmaker
    # command: /work/btcpool/build/run_simulator/simulator -c /work/btcpool/build/run_simulator/simulator.cfg -l /work/btcpool/build/run_simulator/log_simulator
    command: tail -f /dev/null
  user_list:
    image: btcpool_user_list
    build: ./list_id_api_url
    container_name: btcpool_user_list
    ports:
      - "8080"
  mysql:
    image: mysql:5.7
    container_name: btcpool_mysql
    ports:
      - ${MYSQL_PORT}:3306
    command: --max_allowed_packet=32505856
    environment:
      - MYSQL_ROOT_PASSWORD=root
    volumes:
      - ./sqls/bpool_local_db.sql:/docker-entrypoint-initdb.d/local_db.sql
      - ./sqls/bpool_local_stats_db.sql:/docker-entrypoint-initdb.d/stats_db.sql